language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "FklZeQt61mO2i8seMuwCwpnotKMrVZYOtEFxVm90XcoFjQO8yRNIAid62naBedZWIZvlLDslox+T+rL4hCS/adDjW
4d8D4GQAIgLG2mVFXSr0qacns0ZQuc4hHol5uiGIzej71RtXwhwVJ2VcYzR7nFGGdMJCRZ6kn4u40auea6pxU8v5X7o/OhgoC/7t
iKorEgZ3+H4AKQVKjXrDIGtFNn7ONMGRz1Zm2tlOl2ikMMuafu1yUFUG7s9telEbP1VJ3j7CKMmK/wS10EQsXc4z1kI1aSQC1Z8/
vih2EUVRm3g31F0oNkKdat5ABJtDyhpni4PA3qoZ5aVKKnJaVZtI0APDmDeL9kzu6a9yU65MrCQ6BQyeR4lcs8FYm6Zp0iIC46W3
y9SuSSNUAxZGUn6CWAAOFRDntZY1iuMxkjsTAXrjj9IvpH5HHtF9Wg7WLFbfBeXTJKwuNkN+6wZieIuBtpF/C4joFphCuY0E3y5R
h2p6SetxQ8pz0g36vVKV/1y8VB3utaouHJVvEYhMsmerZv3WR5kNe/wT7jYvsm38CFr9xYaNu9Rtyqf4FaNCLwKxtjtXrw5bztBH
ZbjRPrm0bBA0Ns0jTJUiUGbRzUOoQg1F23RE7cLQ7j2+y3g2q9WgV/kkxoS/EVdWvXroQaoUOpEGVa9PvHlz5/wHrDyalg="
    
jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  